### PR TITLE
Adds a few more settings

### PR DESCRIPTION
**Pull request by JYZR**
Settings for these options have been added:
- `-pa` <- `pa_dirs`
- `-pz` <- `pz_dirs`
- `-o` <- `output_dir`

### CODE REVIEW

**Comment by JYZR** [comment]
`pep257` failed but I don't see how that's related to my changes

**Comment by teh-cmc** [comment]
Heys @JYZR, thanks for the PR.

As for why `pep257` fails... I guess the spec has changed since the last time Travis has run on this repo? I'm not sure, I rarely do python. Anyway, I'll fix it.

**Comment by teh-cmc** [comment]
We're good.

**Comment by JYZR** [comment]
Great, thanks!

**Comment by JYZR** [comment]
Could you also add a tag for this? Seems like Package Control currently prefers the tag `1.0.3` over `master`.

**Comment by JYZR** [comment]
Interestingly, the Package Control site shows version as 1.0.3 but the README from master

https://packagecontrol.io/packages/SublimeLinter-contrib-erlc

**Comment by teh-cmc** [comment]
Done. Apologies for the delay.

**Comment by JYZR** [comment]
:+1:

**Pull request merged**
